version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: Monitor
      POSTGRES_PASSWORD: Doremifa
      POSTGRES_DB: SyspymeDB
    ports: 
      - "5432:5432"
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
      - './models/schema.sql:/docker-entrypoint-initdb.d/schema.sql'


